HttpAddress: "*"
HttpPort: 5026
SmtpAddress: "*"
SmtpPort: 5025
# Your token for the Telegram bot, get it at https://t.me/BotFather when registering the bot
TelegramBotToken: TELEGRAM_BOT_TOKEN
# Define here a list of email addresses and telegram chats that will receive emails sent to these addresses.
# Use an asterisk "*" instead of an email address to send all emails to some telegram chat
Routing:
-   EmailTo: "*"
    EmailFrom: backup@mrhyde.loc
    TelegramChatId: TELEGRAM_CHAT_ID
    Prefixes:
    -   RegexpSubject: "\\ASuccess"
        Prefix: "🟢 "
-   EmailTo: "*"
    EmailFrom: upsmart@mrhyde.loc
    TelegramChatId: TELEGRAM_CHAT_ID
    Prefixes:
    -   RegexpSubject: "supply\\s+normal"
        Prefix: "🟢 "
    -   RegexpSubject: "supply\\s+fault"
        Prefix: "🔴 "
-   EmailTo: "*"
    EmailFrom: "*"
    TelegramChatId: 12769849
# Logging Level. Set to Debug to see the details of the communication between your mail program and the relay.
# Set to Error to see less information
Logging:
  LogLevel:
    Default: Debug
